### ISSUE TITLE
No code ?

### ISSUE THREAD

**Issue by gl-yziquel** [trueagi-io/hyperon-moses#1]
Just cloned this repo. No code.

Anyhow, looking forward to see such a port.

**Comment by ngeiswei** [comment]
There's code now.

**Comment by gl-yziquel** [comment]
Thank you. Really look forward to play with hyperon metta. Juste a side question: is it possible to turn hyperon metta into some kind of production system like the SOAR kernel (which I've been investigating recently...) ?

**Comment by ngeiswei** [comment]
It will certainly be possible, with enough work.  A number of things would need to be added such as streams (either in pure MeTTa or via grounding to existing Python or Rust data structures).

**Comment by gl-yziquel** [comment]
> It will certainly be possible, with enough work. A number of things would need to be added such as streams (either in pure MeTTa or via grounding to existing Python or Rust data structures).

@ngeiswei  Thank you for your reply. Is there any place like some IRC channel where it could be possible to hook in passively with the conversation going on around MeTTa ? Sorry to ask here, but, well, I don't quite see where else to ask.

**Comment by ngeiswei** [comment]
Sure, if you provide me your email address I can send you an invite to SingularityNET's mattermost server.

**Comment by gl-yziquel** [comment]
> Sure, if you provide me your email address I can send you an invite to SingularityNET's mattermost server.

Done.
